services:
  postgres:
    image: postgres:17.4-alpine
    container_name: car_logger_db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_logger
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
